# To run locally
# npx techdocs-cli serve -v -c docs/mkdocs.yml
# 
site_name: 'Internal Blog for Bob Cotton'

theme:
  name: material
  features:
    - navigation.sections
nav:
  - Home: 'index.md'
  - Blog: 
     - 'blog/index.md'

plugins:
  - techdocs-core
  - blog:
      post_url_format: "{date}/{slug}"
